[package]
name = "agrg-sh-d-util"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
serde = { version = "1.0", features = ["derive"] }
hex = "0.4.3"
iced = { version = "0.12.1", features = ["svg"] }  # Valid features for 0.12
serialport = "4.7.0"
chrono = "0.4"
rfd = "0.12"
